// Self-contained Bayer/BlueNoise/Riemersma dithering Web Worker
// Duplicates minimal logic from dithering.ts to avoid import resolution issues in workers

type BayerSize = 2 | 4 | 8 | 16
type WorkerMode = 'bayer' | 'blue-noise' | 'riemersma'

function generateBayerIndex(size: number): number[][] {
  if (size === 2) return [[0, 2], [3, 1]]
  const half = size / 2
  const sub = generateBayerIndex(half)
  const m: number[][] = Array.from({ length: size }, () => new Array(size))
  for (let si = 0; si < half; si++) {
    for (let sj = 0; sj < half; sj++) {
      const v = sub[si]![sj]! * 4
      m[si]![sj] = v
      m[si]![half + sj] = v + 2
      m[half + si]![sj] = v + 3
      m[half + si]![half + sj] = v + 1
    }
  }
  return m
}

function toBayerThresholds(m: number[][]): number[][] {
  const n = m.length * m.length
  return m.map(row => row.map(v => Math.floor((v + 0.5) / n * 256)))
}

const BAYER_MATRICES: Record<BayerSize, number[][]> = {
  2: toBayerThresholds(generateBayerIndex(2)),
  4: toBayerThresholds(generateBayerIndex(4)),
  8: toBayerThresholds(generateBayerIndex(8)),
  16: toBayerThresholds(generateBayerIndex(16))
}

// Inlined blue noise texture (generated by scripts/generate-blue-noise.js)
// Importing from blue-noise-texture.ts would require bundler support in workers
import { BLUE_NOISE_TEXTURE } from './blue-noise-texture'

// Palette entries are [index, r, g, b]
function getClosestColor(colors: number[][], r: number, g: number, b: number): number[] {
  let minDist = Infinity
  let closest: number[] = colors[0]!
  for (let i = 0; i < colors.length; i++) {
    const c = colors[i]!
    const dr = r - c[1]!
    const dg = g - c[2]!
    const db = b - c[3]!
    const dist = dr * dr + dg * dg + db * db
    if (dist < minDist) {
      minDist = dist
      closest = c
    }
  }
  return closest
}

function nextPowerOfTwo(n: number): number {
  let p = 1; while (p < n) p <<= 1; return p
}

function hilbertD2XY(n: number, d: number): [number, number] {
  let rx: number, ry: number, t = d, x = 0, y = 0
  for (let s = 1; s < n; s *= 2) {
    rx = 1 & Math.floor(t / 2)
    ry = 1 & (t ^ rx)
    if (ry === 0) {
      if (rx === 1) { x = s - 1 - x; y = s - 1 - y }
      const tmp = x; x = y; y = tmp
    }
    x += s * rx; y += s * ry; t = Math.floor(t / 4)
  }
  return [x, y]
}

function runBayer(data: Uint8ClampedArray, width: number, height: number, indexedPalette: number[][], bayerSize: BayerSize = 4) {
  const len = data.length
  const size = bayerSize
  const matrix = BAYER_MATRICES[size]

  const colorCache = new Map<number, number[]>()

  for (let i = 0; i <= len - 4; i += 4) {
    const x = (i / 4) % width
    const y = Math.floor(i / 4 / width)
    const row = matrix[y % size]!
    const threshold = row[x % size]!

    const r = Math.max(0, Math.min(255, data[i]! + 128 - threshold))
    const g = Math.max(0, Math.min(255, data[i + 1]! + 128 - threshold))
    const b = Math.max(0, Math.min(255, data[i + 2]! + 128 - threshold))

    const key = (r << 16) | (g << 8) | b
    let closest = colorCache.get(key)
    if (!closest) {
      closest = getClosestColor(indexedPalette, r, g, b)
      colorCache.set(key, closest)
    }

    data[i] = closest[1]!
    data[i + 1] = closest[2]!
    data[i + 2] = closest[3]!
  }
}

function runBlueNoise(data: Uint8ClampedArray, width: number, height: number, indexedPalette: number[][]) {
  const len = data.length
  const colorCache = new Map<number, number[]>()

  for (let i = 0; i <= len - 4; i += 4) {
    const x = (i / 4) % width
    const y = Math.floor(i / 4 / width)
    const threshold = BLUE_NOISE_TEXTURE[(y % 64) * 64 + (x % 64)]!

    const r = Math.max(0, Math.min(255, data[i]! + 128 - threshold))
    const g = Math.max(0, Math.min(255, data[i + 1]! + 128 - threshold))
    const b = Math.max(0, Math.min(255, data[i + 2]! + 128 - threshold))

    const key = (r << 16) | (g << 8) | b
    let closest = colorCache.get(key)
    if (!closest) {
      closest = getClosestColor(indexedPalette, r, g, b)
      colorCache.set(key, closest)
    }

    data[i] = closest[1]!
    data[i + 1] = closest[2]!
    data[i + 2] = closest[3]!
  }
}

function runRiemersma(data: Uint8ClampedArray, width: number, height: number, indexedPalette: number[][]) {
  const N = 32
  const r = 1 / 8
  const weights: number[] = []
  for (let i = 0; i < N; i++) {
    weights.push(Math.pow(r, i / (N - 1)))
  }

  const errorBuf = new Float64Array(N * 3)
  let bufHead = 0

  const side = nextPowerOfTwo(Math.max(width, height))

  for (let d = 0; d < side * side; d++) {
    const [x, y] = hilbertD2XY(side, d)
    if (x >= width || y >= height) continue

    const i = (y * width + x) * 4

    let eR = 0, eG = 0, eB = 0
    for (let k = 0; k < N; k++) {
      const slot = ((bufHead - 1 - k) % N + N) % N
      eR += weights[k]! * errorBuf[slot * 3]!
      eG += weights[k]! * errorBuf[slot * 3 + 1]!
      eB += weights[k]! * errorBuf[slot * 3 + 2]!
    }

    const origR = data[i]!
    const origG = data[i + 1]!
    const origB = data[i + 2]!

    const adjR = Math.max(0, Math.min(255, origR + eR))
    const adjG = Math.max(0, Math.min(255, origG + eG))
    const adjB = Math.max(0, Math.min(255, origB + eB))

    const closest = getClosestColor(indexedPalette, adjR, adjG, adjB)
    const chosenR = closest[1]!
    const chosenG = closest[2]!
    const chosenB = closest[3]!

    data[i] = chosenR
    data[i + 1] = chosenG
    data[i + 2] = chosenB

    errorBuf[bufHead * 3] = origR - chosenR
    errorBuf[bufHead * 3 + 1] = origG - chosenG
    errorBuf[bufHead * 3 + 2] = origB - chosenB
    bufHead = (bufHead + 1) % N
  }
}

interface DitherMessage {
  mode: WorkerMode
  pixels: ArrayBuffer
  width: number
  height: number
  palette: number[][]
  blockSize: number
  bayerSize?: BayerSize
}

self.onmessage = function (e: MessageEvent<DitherMessage>) {
  const { mode, pixels, width, height, palette, bayerSize } = e.data
  const data = new Uint8ClampedArray(pixels)
  const indexedPalette = palette.map((color: number[], id: number) => [id, ...color])

  if (mode === 'bayer') {
    runBayer(data, width, height, indexedPalette, bayerSize ?? 4)
  } else if (mode === 'blue-noise') {
    runBlueNoise(data, width, height, indexedPalette)
  } else if (mode === 'riemersma') {
    runRiemersma(data, width, height, indexedPalette)
  }

  const transfer: Transferable[] = [data.buffer]
  self.postMessage({ pixels: data.buffer, width, height }, { transfer })
}
